/**
 * 报文传输协议：
 * RSA对加密解密秘钥和加签解签秘钥进行加密
 * DES通过秘钥进行数据的加密解密和加签解签
 * RSA通过公钥加密、私钥解密
 * <p>
 * 加解密秘钥pingKey和加解签秘钥workKey为随机生成的24为字符串
 * mobKey为通过RSA将pingKey和workKey拼接然后加密生成的秘钥串
 * <p>
 * 步骤：
 * <p>
 * 1、通过方法RsaUtils.genKeyPair()生成公钥和私钥（也可通过网络工具生成），分配给下游商户
 * 下游：
 * 2、随机生成两个秘钥（加解密pingKey和加解签workKey）
 * 3、通过RsaUtils.encryptByPublicKey()和公钥加密得到mobKey
 * 4、通过DesUtils.encryptByKey()对数据项加密
 * 5、通过DesUtils.encryptByKey()对数据项加签，得到sign
 * 6、将sign、mobKey、加密的数据，组装成报文传输
 * 平台：
 * 7、获取报文中的mobKey、sign
 * 8、通过RsaUtils.decryptByPrivateKey()和私钥解密mobKey，得到两个秘钥（加解密pingKey和加解签workKey）
 * 9、通过DesUtils.encryptByKey()对数据项加签，对比sign值验签
 * 10、通过DesUtils.decryptByKey()对数据项解密，得到明文数据
 * <p>
 * 返回下游的报文加解密和加解签流程同上
 * <p>
 * （代码有些判断不严谨，请在实际的代码中进行完善。）
 */

package com.omv.common.util.signature;


import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.omv.common.util.httpclient.biz.HttpClient;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by zwj on 2018/8/11.
 */
public class Test {
    static String str = "{\n" +
            "\t\"instanceId\":\"I234234322\",\n" +
            "\t\"notifyUrl\":\"www.baidu.com\",\n" +
            "\t\"timestamp\":\"1231239233\",\n" +
            "\t\"data\":[]\n" +
            "}";

    public void sendMessage(Map<String, String> params) {

        EncryptManager encryptManager = new EncryptManager();

        params.put("name", encryptManager.encryptStr("周星星")); // 加密
        params.put("sex", "男");
        params.put("age", encryptManager.encryptStr("10"));

        params.put("mobKey", encryptManager.getMobKey());

        // 签名
        SignUtils.getSign(params, encryptManager.getPrivateKey());

    }

    public void receviceMessage(Map<String, String> params) {

        // 通过mobKey获取pingKey和workKey
        String mobKey = (String) params.get("mobKey");
        EncryptManager encryptManager = new EncryptManager();
        encryptManager.parseMobKey(mobKey);

        // 验签
        if (!SignUtils.verifySign(params, encryptManager.getWorkKey())) {
            System.out.println("验签失败");
            return;
        }

        params.put("name", encryptManager.decryptStr((String) params.get("name")));
        params.put("age", encryptManager.decryptStr((String) params.get("age")));
    }

    private static String publickey = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4W7KA25AvgoMjwnxo+cdNhTASbEGQOQkgulOac1oS4YHL9eb8QFkx++CZffU21UqgIUpAo8qR1wf6/3j8TECnU147671rARINJWLl4Oj4KRInt5FTjBdHC6M6NBQBpQv6xFrtlq8UGORE9LS4HnPoKGoKiIyTPEO18ilsNkHDuwIDAQAB";
    private static String privatekey = "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALhbsoDbkC+CgyPCfGj5x02FMBJsQZA5CSC6U5pzWhLhgcv15vxAWTH74Jl99TbVSqAhSkCjypHXB/r/ePxMQKdTXjvrvWsBEg0lYuXg6PgpEie3kVOMF0cLozo0FAGlC/rEWu2WrxQY5ET0tLgec+goagqIjJM8Q7XyKWw2QcO7AgMBAAECgYBujibEmWak5wpHdoju1uMK/NTwJ1VF7L4pjzM1ivk4G12f903WdaxHijmNMnjLsiq3Tl9d1htTS/UwMuXVvtCBwWelrTxihNQzcNgS1NNps4fXS6RfhTfGLJLi2tb3AjMBaOgtGosl7GTcJwNewbJr4fv/ElMeH+YSc8Lw79MVOQJBAO/unjJNqjIN/dzcASuLZlV+g7q6GIZp1kqonvySqBJJJtMIpXi7+0uAuxY6id37qz7crqEzRyGuJj8pZnYaf28CQQDEtFLNlVpCkrD2eAfsQYYvxsTNGmFsgmhURO0i8uS4e4ey6JntDh6l75u+a1f6nugh1saoIYDfTPMK7yj979p1AkBRHQ6GWxNK0MgePpJ2si3qgVbvbbKU3nr/ynnVUY9YfzqM5cNrScHvCJo3LZsmXMrL+bdf8AIANOvhNpHZI6QpAkEAlxwYCErV/hKG07C+FWb42LcP9Khxc1RzJVmV+qUxw+9R/cTmis+wB7WcpZn9ClEM7wH5tquWPvT0ONAlY37hCQJAGQ1ITivxyRperaXnHrUcw2b874b0I9jaWpJqh2aGgeHX5KWRQdHJvtEPJVT4lWjXylm5jZb2AGqsgGVK2Bc/tA==";

    public static void main(String[] args) {
//        String datddd = "{\n" +
//                "            \"address\": \"string\",\n" +
//                "            \"airConditioningCost\": \"string\",\n" +
//                "            \"alias\": \"string\",\n" +
//                "            \"buildType\": \"string\",\n" +
//                "            \"buildTypeName\": \"string\",\n" +
//                "            \"buildingCode\": \"string\",\n" +
//                "            \"cityName\": \"string\",\n" +
//                "            \"countyName\": \"string\",\n" +
//                "            \"electricityCost\": \"string\",\n" +
//                "            \"elevator\": true,\n" +
//                "            \"floor\": \"string\",\n" +
//                "            \"floorCount\": \"string\",\n" +
//                "            \"gasCost\": \"string\",\n" +
//                "            \"houseSpace\": \"string\",\n" +
//                "            \"houseType\": \"string\",\n" +
//                "            \"houseTypeName\": \"string\",\n" +
//                "            \"householdNumber\": \"string\",\n" +
//                "            \"leaseStatus\": \"string\",\n" +
//                "            \"leaseStatusName\": \"string\",\n" +
//                "            \"leaseType\": \"string\",\n" +
//                "            \"leaseTypeName\": \"string\",\n" +
//                "            \"maintenanceCost\": \"string\",\n" +
//                "            \"name\": \"string\",\n" +
//                "            \"note\": \"string\",\n" +
//                "            \"parlourNum\": \"string\",\n" +
//                "            \"provName\": \"string\",\n" +
//                "            \"roomCode\": \"string\",\n" +
//                "            \"roomNo\": \"string\",\n" +
//                "            \"roomNum\": \"string\",\n" +
//                "            \"roomSpace\": \"string\",\n" +
//                "            \"thirdNo\": \"string\",\n" +
//                "            \"toiletNum\": \"string\",\n" +
//                "            \"unitNo\": \"string\",\n" +
//                "            \"waterCost\": \"string\"\n" +
//                "        }";
//        JSONObject obj = JSON.parseObject(datddd);
//        JSONObject json = JSON.parseObject(str);
//        JSONArray data = json.getJSONArray("data");
//        for (int i=0;i<=50;i++){
//            data.add(obj);
//        }
//
//
//        EncryptManager encryptManager = new EncryptManager(privatekey,publickey);
//        Map<String, String> reqParams = new HashMap<>();
//        json.forEach((k,v)->{
//            String val = json.getString(k);
//            if(k.equals("data")){
//                reqParams.put(k,encryptManager.encryptStr(val));//对 data 加密
//            }else{
//                reqParams.put(k,val);
//            }
//        });
//        reqParams.put("mobKey",encryptManager.getMobKey());
//        SignUtils.getSign(reqParams,privatekey);//加签
//        SignUtils.verifySign(reqParams,publickey);

//        String result = HttpClient.conHttpByJson("http://119.28.135.68:8765/service-supervision/scrt/data/house/batch",reqParams);
//        sendMessage(reqmap);
//        Map<String, String> reqMap = new LinkedHashMap();
//        for (Map.Entry<String, Object> entry : reqmap.entrySet()) {
//            String key = entry.getKey();
//            Object value = entry.getValue();
//            reqMap.put(key, value.toString());
//        }
//        EncryptManager encryptManager = new EncryptManager(privatekey,publickey);
//        encryptManager.encryptMap(reqMap);
//        encryptManager.decryptMap(reqMap);
        String mobKey = "ULzIZ/k1Iqm6tPJFoT2b1nbRdSDqgJVtR56vyU2MGk386YZxykUuaEuy3kTjir5NrGTqeE7XjMFFuMZRbKsHYl4b6P53ynAWhMKMZyoxPYZyxr+3fGPDmOUc+yw4FYyfGey4IoLHxvKSWwAvcM+rrj2SQuAs89ulIiQfJNM16lA=";
        String sign = "jfMDaLCaT7PETCt26u20nVrxqpzxyhJ6XCegPUmzsXONA0X35DqQ+hFBpROqfdPENC7nbPaOAJEb5I8ZmFYuoimh2Qt13NwDaUB3D+7GGHjEVwrirm5uro/yuXlzLabE5IZqujaqJwoLQV73xgzqsxQchYJxLwxx1JjKv/DWzEk=";
        String content = "MTMzYjM0MTU0N2NiZDczNDQzY2U0MmY1MWE5ZWYwZjRhY2JjZDRmMDcyMTNhYzY3Y2JiMzI1ZTllMmUyNmNiYjNkNWEzYWUyZmIwNWJiMDYwZjhlOGNkMzQwYzYzYmY4YjRhMDY3YjY3NmJlMGE4ZDMzNWE2MWVjOTkxN2IwYTUwZWU0Nzc4YTNjOWFhNTUzNjQyNTBlODAyOGE2ZjhlMmE1ZTUxZDc0NTdkZTYzNDg4ODNhZDNjYjgxODEzZTA1YmJiMzk4ZWJiNTVlMjA2YWU4NmQ4NjAwZDg0MzI2MTYyY2UwYTI5OWY4ODY3N2EyODlkMTdjMTkzYTAwMjVjYjMyZDQ1YzJkMzcwOTBlYjhhZDEyYjdiNjNlZDNjY2NjMjNlNzYzYWRlNzI3MWU5YTU2ZGNlZGIwMGY2MWY1ZGZhOGZiZjMwYmFlYmM4MmRlZWJlMTBiMWEyMTc3OGYxNzgwYjA4N2MwNDA1NmE3YjZlNWYxZDkzNjk0YmI4NmZmNDk4NzI1ODJiM2Y3ZDlkY2Y3YzA3MDg3YzY5ZGViYjZmZTI0Mjk2NmQ3MDQ3YzZlZTA5ZTljMDljZGJkMjk1NTFmZjhiMDk2NjMwNDNhYzdmMDQwOTI4YzUyZWNjNTZhZTczYjgxOWE0M2YxMTg0NDM2ZmIzNzQ1ZGNlNjNkYjMzNjMzOGE1MTRjODA1Zjc2ZWRiNWQyMmJjMGI2M2UwNmMzZTg4ZDJiNTE2YjI4MDM3MDdhODMzZTJiZTJkZGFlMzQ4NGQ5M2YxMzQwM2MxYmYyMmIyMTBjNTM4MGJmODQ4MDZiOTVlNDVmOGJmNjc0NGQwMzk1MDFjOGEzYzM4YzIxNzlmNDdlN2VlODI3NGVjM2YyYTAzYzQ5N2Y4N2FmZDA4ZDBiMzM3Y2I2MWQ0MGMyNjE5NDUwYTQyNmNlOTEwNDFhMGMzNjMyNDdlOTlhZDA2YmEwYjBmY2IyNGUwMzlhNGFiZmQyMGNlOTBkOGU0ZjlhNmI1YWM3YmRhMmU5MTIxYWJjYmM3ODU4M2FhNzAwOWVhYzNmYzIyYzgwYThhNjZlZTI4MGM3ZTE1YzdhOWQ2ZmY2ZjhkNDZiNjliYWU1OWQ2ODdmZDE4ZTI5ZWNjMzFiNTgzZTM5NDUxZjgxN2FmNjRhNzU4MDg1OTU1OGE0MWRiMjJiOTMxNTdkYjgxN2UwOTk0NDA1YWEwMWYzOWJhMTBlMDlkOTUyNzE0NDIxMTAxNzViYWMyNTE2ZmJiMDY0OTcwZDgxY2ZmNjJkNzE1MzYyYmZlNmYyYWQzNzJlNzIwYzg3Njk0NmNmYWUzNmRhMjg5MzIyYTgyZThjOTU4NTBmMzI5OGZjMTMzNDdiMjQyNjczYTlmYThiM2YxMDBiODFmNjBhN2UyZjdlZDY4YzhmMDRkNjM0ZmQyOTI3OTE0Y2VmYTM0MzM0MTAzN2Q0ZWE2NGEyYzVlZjg0YjFiNWJiYzYwZDBlMjZlMjY3YTAxYmE3ZTkyYmM2NTA0ZTBjZTZiZjgwZTVlOTk2ZTY1OTJlZWQ3ZjFhZWM3NGNkNmM2NzkzM2U3MTk3MzQ5M2VmOTk1NGIwNjk5NjZkNmQ4NjY1YWYyMTczMDc4MzQ4MzYwZGJkNmZjZTkyODZjZjBmNDc0NmIxMzhmYWUxMmE5MTZmN2M0NjJmY2ZhOGM4NWMzZTM4ZTY1MzBjOTA4OTEzN2NkOGNiYzdlNzIyNWVkNzRhODNmN2Y5YTkzNmNjMTczZmMwOTk2ZGM0NGE4OTAxMTUzMmZmYjRiMDg3ZTkxMzQ4YTY2OGVmN2VjMmI0YzRhY2Q2YjAwNDQ1ZTE0ZGQ5MmRlZTM4MTAwYzlmNmJmMGMxYmJjMThkNDNhNzM1NjA0ZWZhMzBmZjE5ZDI1OWUyZmYzYTE1NjFmNzBjZDY0NDA4YWFlNzEyMmEyZjYwZmY4M2Q1MzA1NTg3YWM3Y2M1NTA4YjRkMzAyY2YxODAyN2RiZTYzZTBlOGVjMDAyNDE2MzdmOTk5NjNkOTk4YzFjYmZkNzFkMDMyOWRhYjhiMGJiMDUxYmVjZTcyZTY5ZWI1Mjc3OWY0ZDFmODVhZjU5YTQwNDNmMjllM2ZjMTgwYjI5ZWRmYjM3ZjZkMjcwYzY5NTU0Y2RkNGFiYzg4OTZlNWQ0ZDM3ODg5NWY0NTQ4OTFhN2IwZjk0YzY5MmM3MDVlYjAzZTY3NmViNmVmODM3Njk0NTJmOTJiY2U0NDI1NDQ3OTQwZTg4NmE1OGZmYTlmMTY5OWMxNTVhZWI0MjIzMjI1MWY3NWI1YTY5YzgxZmRkNGE1Y2U0N2ViZGUyMTI0MGUyZmE3NWVmNzU2ZjQyMzkzMDk3Yzc0MmRhNTY1YWEwYzk5ZTY3MDVmNmEyNzljZjlmOGMyMWJkMWVkZWIyZmY4N2I1MDYyZGI5NzM5ZGU3MWRjZThlNmNlY2ExOTlmMGY1ZTQwYmQxMDg5OTgxYTQxM2Y5NmFjN2Q3NmQzNmRiNGUwM2VjOWIwNmMzNWJiNmMxMmI4YWNiY2U5ZWI0YTdlN2E0M2ZkNGI5NzRhYjE3ZWMyMzIwNDg2ZmQ3YjI0MzhlMzQ1N2Y5YWNhZDA5MDk3MTZmYjlhNTM5MjNhOTI2YmRmYzM0MjJkOWEyMTljYWJlMzVmODZlNjRlY2I2N2VmMjk3NjVjNTMyN2NmNjdkYmUyMTkxNjk1MzlhNGUzYWQ5NDFjOWI1YjU2ZGY2MmIyNzVhMGNkYmU3OWI2NDY4NGE3OTJlMjNkNzIyMGE0NTI1OTg2NWQzZTMzYzZlZmRlZWQ5NmI3ZTY0MjQ4MTk3YTQ4MWEyMDk1ZGQ3Yjg0YzdjNzE0ODYzNDk3ZjVlMWVhZjFmZGFkNWYzNjYwNGJmNjlmYjRhN2E0OWJkNWIzNjE5NGVhYzVhNDY0YzYxNDAyNDA0MjIyNDQ2N2YwN2UyNTE4OWFjYThhNzVhN2E1YmYzZDEzODg1NDRkN2JjNjE3MWIyZDgyNzk1ZmIxMGRiNDhkYmQyYzY2MTMyNGQ4MGFlZmJhNDg2ZjdhNTA0N2YxZWNjN2NhYTVhYjYxOTFmNGU3YzZjMGQzNWYyMzBjODM4NzU5MjllY2VjZjcxNDhlNGExYWQ3ODM4OWQ0MDJkZWMzOTViNzJiZTE5Yzc5ZjVlOThkOGU5NDRkZjBmYzljY2RkOWU0YjZhODE1MzQwODM2MDAzMDg3ODUwMDFiMjZkNDg1ZGRmNzVmY2Q5ZjUxOWU3MjUxZWQ1NDNjNDcwMTQxZWQ4Njc0ZDhlNzQzYTA3ODIwNDJiMzY1YTFkNjgwM2ZlMzI4MjdjNTFjZTJiYWQ4N2RlNzQ3ZjdiYjkxY2IzZDYzOGZiMjFhZTMzZDE2M2YzZTBmNzc1NzUzODdkN2M2YzUwMjRmZTI4ZWU3ZGIzYmM4MzI5YThlZGM3Njg4MmY2ODFlNTlhYTU3NTljZjAwYTQ1OGIwM2JmNmUzYzczNTlmYjI3NTM2Y2NjOWQxMTQ2NTgxMmNiYzU3Y2QxZmRkMjgxZDhhNDQxMTg1ZWNmOTQ0NzkyNWQ0ZDI4NDI2M2VmZjYzNGU3OTc3OTY0MGNlMmVjZDRjNjcxNTY0ZGExMDJkYTU5ZDIzMjU3MDRmNWIyZjczN2Q5MjFmZWMzNzZkZGVjYzk4MTA1N2U4MTMxYjJkODk3ODY0N2YzYjA0OGU1MWE0ZDFmZTViMDBlMjJkMTJmN2VjNGRhNmJjMmUwNjI1M2FkMmJjYmE0ZTIxMmIzN2U3ZGM3N2FmYjRkZjU3MTU3YzQxZDBjZDYyMGE1YzA0OGY4NDdiZTA2YTYxYzc5ZTA0ZjE5OGRjODgxOGE5MWU4NDg0YmNlYWNlZDE0NTgzOTNjMzE1ZTcxNDZiYjI4Zjg0M2FlMjI2ZTIwNWEyNDc0ZjY4NTczYTc2ZjQxYTQ1ZmMxMDJmYTMyZDVmM2U0OTY4NjIxZjY5ZDc1N2Y4ZWQyNDg3ODViMWE2MjQ0YzBhN2Y0ZmRhYzNmYzhlNzgwZTRhZjZlMDY3M2NhYWRhNjQ4OGRlODA1MTgwZGQ0YjQ3OTdmMDI4OTViNWViNjVmZDAxNDFlZDdkY2EyZDU3MzRjNGVlNjFjYjkyMjc1NTc2ODBlOWNiZmZkMTMwNjE1N2EzMmViZmJlOWExZWQzZTIyNTRlNjJhMjU0YTI5M2YyZjY2YzIzMzFkMmUwNmYyN2E0YWFmMDgxYTAxMzZjZmEzZjY4MjkzYjc4YTU1MDBkYTNmNjQzZDJjNmM0OGIwMWVjZDI5MzkzOGNlM2E0MWIwMzk0Yjg5MWY2MjQwZTRkMzYyOWY5ZGMxOGJhNjljZjI0NDE3MjY0YjYxMjNhYTA0ODAxYmJkZDJmNWI0M2QxNmVmODk4ODE4MTM0ODM2NmIwZWM5YTVkYWE0ZDI1NDQ0NjQ2ZGM2ZjkyMzk2NTY5OTYzMTE4ZjI4NTY1OGYzMmY1NDk5ZTZhODQ0OWYyNDRhODJmZThkOTQxNmI1YzllZjQyYjBhMDIwNWE4MDU0ZDUwMDY5NWRhMjhhMzQ5NzJkMzdlNDM4NDQxODRlMjhlYmNjMGQ4NTFjZDU4NTkyZTM0NDQwYmI1ZGE4ZjQ0MWY1NjM5MTM5NjA1YzllYzIxOTJjMTdhNmYxZTI5ZTAyNzE3ZTQ4N2MzNmI0NzA1ZDdkMGY3OTcwOGM4YjI4YjBiNzMyZWRjZmU1MzQyNjk1MGI4NGJkNzU3YTczYmI1OWRjM2E4YzI4ODFjMDY2YWNhNWQwNGU0NTkzOWZmMjM3MTFiMDQ0N2RhMmQwZmNkODkwZDVjZjQ4NDlkOTY3ODZhMTIyMzAzYWRhZTEzNjFhNGIxMWVjZDg4Y2ZmNTc0Y2JlMjY1MzY2MjNiZDVhN2I1NDY5MDE0YTZmMDIwZmFhYzJmNWE0ZTllZWY1NTA4OGNkMDgwMjgwODdjY2UzODRmZjBjZWRhZTc4ODc1YjY2M2MzYTY5NDEzYTI1ZTUyYWFlYjE1YjM0ZmIxYjAxZWQ0ZTNkZjk1MWViMDdjMjYyZjBjMDZmZmMxYzcyZWU5NGNlN2ViOTI2Y2U3M2M5OWNlOGMwMDhmYWVlNGJlOWI4MGU0OGRlMjhhODZiNTgwMjAzNGEyZGI1ZDA5ZTBkOWUzYWUyMmNiYzk1YWQ3ZDc4YjQ4NDM5MTA4MGFiOWIyNjhjYjA3NWM0ZmU0YTQ0ODQyM2QzOTU1MzY4YjBkNjBkMmNiZTM0ZjBlYmMyZDg5MDJlY2JiNDQxMWYwZjkzYzAwZTA2NWNjOWVjMTY3MTQxYzVlNTY0MzM3MGZjYTUwNWYyZTQ3YzJmMmRmMzY2ZDRiMzA5YzhlN2NjYzFjMWJiZTU5YTE1ZTU1M2IzZDJiYzBmNWFhMzFiZWZiY2RiMzFmYzcyYThjMGFkNTliZTBlZWVhMTUzNjE3MDM5ZGQ3MWY1NjA4ODNkYjQ1YTA0NTc4NjdhM2Y3MmU0MDA1N2IwZWE4MTMyZmI5NTgzZGE0ZmQ5ODQ5Y2VjMDlhNDVlOTI3NGFjNGUyZTkzOWQ1Y2I0Yjk5Zjc5NjAxOWI0MDMyM2JlNDQ0ZTkzMDliZTdjOWM0YWUwMzJlMTQyOWY1MjU3ODQ4ZjhjMGJlNDY1ZDAxMDBhZTdhZGRiNGJiZWFiMTEyMzI0MmE0NjQ0YjEwYTI0YzlkMmEzZGExODU3NTdmNDU0ZjcwMzVmMzQ4YmIwYjlkN2QxMzYzOWE1YjA3ZmM5NWZjYzU5MjZiMDNlMzMyOWUxOTZlN2Y4MDAwOGFkYjc5NGFkNDQ0Yzg5ODRjYjYxOWVmNGFmYWQ4NTQzNzczYTA5ODg0NTYwZTc3ZWFmMWE2NTI3Mzg3NjFhYjBhMDU4YTQ1N2E3NGU3YTdlY2NhYWE5ODk2ZTcwNDkxODE0NTUyYWU5YjliYzU0MzAwZWU2OTFkNzc5OWRkZjA5NzAyZDBjMmNmZDlhNDg2MmEzOTJkODM0MGNhOTZlMWNmMjE2NWZjOGE1MjEyYjE2ZmExMzRhMDc3N2E5ZGRmMjFjMTc5MTI3OTE0ZDlhZTM0MTlkMTEwZmUyM2NkOWMyMDdjMWMxYjY4NjU3YjNkZTAzNzFhOWIzNWM2ZGVhMmU5ZmJiMjg1OTM4MzIxOTMwZTJkYWFmOWQ3NGU3NjgzNGU5YTM5ZGI3M2UxMTYyNjAxY2EyNzcxMDdhZWJhZTcyNjZjNzI2M2YzNmRmNzRhZDJmZGE1MGUyNTQ0ZWZhZjc1YjcwMjg1YTQ1NTQxMGU2NzAzNTMwZTdkN2IyNDllM2ZlN2EzYjA4YmRhYjZiNjJiMDAxMjU1MGUzOWYyYzY1YjU4MTA5ZDk2NTY2ODlmNzE3OWU5Y2JlN2VjMzQ1YzkzMDM3MjVhYWM0ZTI0MjFjMzI2MTM1ZmIwZGRlZTNjOTdhMjljMTk0YzY2ZTJjYTc2NThiOWI1YTMwZDFjZjA4OWE4NTNkMzkxZTFmNTA1YTMzZDFjMjA0ZTQ3ZjAzYjk4OTNiY2RjOWJkNTA3MjgwZjIxODI2MjhlNDU0ZmIxMTA1M2ZjYTM1MmJjMmNiMGZkZTM2MDI5MDZjYjM3MjBiNjIyMThmOTc0NGZmZmUxMWU0YThhNGY3ZjcyMWE5Y2JhYmU4NDk0MWE2ZmFhNWViNjk2ZDZiZjBkN2YzOWE0ZjlmYTI5M2IxZDNhOTM4MmY0NGJjYmM5ZjYyZmUzYzdlMmNhM2Y2MzAzYmIyYzAxYjNmNzBhZDZhZTZkOGNjMTNjMmUyZWJlYzEyZGE3MzE2NzQzMjMzMTgxODlhNmEwOWNkMWI1NDI1ZTgzODU0ZTg4ODU5MmRlZGY5Yzg2NDQxOTYwZDhjZjE4N2I5YWNmODVhNDVkN2UzZjA2OTNkM2I3ZTFmM2RiYjhiMGQ0NGQ3ZjBjYzg2ZThlNjk5NjZkZDQ3MGVlYzJjZmJkYzRjNDljYTA3MWFhZDZlODA0Yzk1MGNhYzExYTQyN2U0OWRlNDRlNDc5MDY2ZDA1NTc1ZGY5YjBjNTZjMDgyZDdkMDFhYTJmMTk4NTQ1NWUxZjY1NzRhZjAyZTg2YjIxOTdkZmRmYTFkMGE0ODRlYjYyYzRiNjdmZjZiNDhjMDZmODQ1YjYwODhlN2ExZTM4NTEyNDQ0ZWQ1NTkyOTNjYWM4NzQzMDQ2YTgzNzQ3ZWVlZWFhMzVlYTU4YzFjN2UwMzA0OTgyNDFkMDgyZmU0MGU5M2M1YWY4MTQ4YjY1Y2FiZDY1YWM0MmVkMGZiNzJmMzliMTZkMDU1OTEwNmE1ZWEzM2M0YjU5MWQxODA4Y2M5ODFmNDUxYjRkZTNlYzZiODQyMTJlZGJiMGM5OTVhOTk1Yjg3YWYxNWU2NzVjOTBlNmZhZjA2MzVmNGY4YWFkMjc2NGRhYjZlMzQ5ZGQyZTIxYzJhNTFhMGIyMjFiY2QxNmE2NGRkOWJhNWE2NzgxZTc2NDU4ZTljMDlhODQxYmVmNTg3NDA5NmNjMTViYjAwNGYyNzZlZWQwMjEzMjE1ZDA2NGRhZGY1NzQ1N2VlOGRhNmFkY2UwZWFjNjUyNWRjODg1NzVkZTM0NmNiNTA4YzE4YWJlNWRiNjIyOTczYjhjM2RlODdhOTc5MjkyMDQ1YmU4ZDJkNTJjMWZlN2Y4YmI5Njk5YTBjOWRmODdlY2EyZDM0ZWQ1OTQ1MWY0ZDJjNWE0OWU2NmUzNzZlMjZhNGNlNTA5YTM0ZDg5NjRmYjI4MDRlZjkwZmJhOWRhZTFlYWI1OGQzMWI0YjE3ZGI0MmI3MGM5OTUxYzA5ZThkYTg2M2E2Y2Q0YTI4NjRlYzMxYjYwNWRhMDBjYzBiMzE4MjI4MDc2ZTFlNDMzYjBiOGY4MjZjYTllMWUzNWQ4OTk0YTVlMjczN2RhNzRiOTY2YzUyYzU5YTE2NGRkZGE2NDRiZGI3OGI3NjMwYWQ2NjMwYzAzYTA2YzcyZjNhYmUzZTcxNzU0M2MzY2IwZjEyNjg4YzA5OGUyNjZkYjk2N2M0OGU1NTA1ZWE2YzI3NzdkMmU0NDFhOTljMzE1MTE3MDA2ZTFjNDMzODZjNDAwMTI5Yzc5ZThmMWZiNTI0ZDRiNjZiYzU5MDI0NmNjZTExOWI5NzM0NzgzN2U1MGYzZmY1NTRkMmY4ZmQ0MGQ4YmI1MDM1MzczYmI1YzMzYmZmZTQ2YzY1M2ZkOWFiYzE0ZmRhNjk4YTYzNzJkZDYxZDY0OGYxYzQyNTQxYzM0ZmU5ZjRhYTM4MjhhMzU3MzEwNmQxODQ3NGMxYTRkODIxNDE4OGNkYTNlY2IzZGE0MWMwNjgwNWJiZjIyYTJjNDRhMGQ2Njc1OGY5ZWVhNjY4ZDE2M2JhZWUyOGIwMDBjYzEwZmFhOTQxY2NmMzhjYTMxMDQxZmQ5N2VmZmUyMTFhOTMyY2I2ZjY5NzkyMmFmZTY1ZjFhYzE3ODNlNjRmYTM2MjYyZTE1OTU1YTdjZGRmZjYxOWU4YWZiZGE1NzlmZGUzMDM4M2FjMDQzYmUyMTAxY2Q4ZjRkMTlkMmRiMDY5ZjhiMmI5ZjAwNmFkNDg2MTE0NTMyMWRmNGJmZGJiOTQ2MTY2YjRjMDVlN2M5NjA5ZDA5MDUyMjc5NTViNGU1ZTMzYjQ4MjEwNDllMDQ3NjhhMGQ5N2I0YmY3ZGZjMDFiODVkMDEwMjI1NWJhNGEwOTQ3ZDRmYWM2MGM3ZmI4ZjE5YTUwMzY4ZTIzMmU4YTBhZDBiOTcxNDA2NGIwOGE2N2E4YTg3ZjU1OTliZTgzYWQxYjBmNmMwOTM3YTkxNDIwZDFhMTI1Yjg5YTY4NWZmNTY4ODFlZDM2ZTg4NzZmMjIzZjg2OWY4MTZjNzI5N2FlMmFhMDUzMzUyZmFhOGFlZjBmNTU5NDY0YzdmNGI4ZmVlYmIzYzVmOWVhNmUyOWJmNmJlMGM4ZmI3ZTA1NDdmNzYwZTMwM2U1ZWFjZmVkZWY4NTg3ZDc2YTYwZmUwY2I5NzViNTQwOTczZTA1ZjYxMTQyNjVlZjEyZjI0N2FlNDM3YzlkMTBkYTc4MjYwNjg4MTAxYTEzMmU2MjY2NmI3ZTEyNjZjNjZlZGU0ZGZkOGY2ODg5OWFmZGE2NWU1MDZjMGQxMTg2YTc5NjM5YmVkNTg4MDEzNjFmNGYzYmQ0YTg1ZWIyNzk5YjVmNTNiMTBmMmYyZDQzY2E0OWZhOThlMjc1ZGEwYTNlNzMzOTc2YWI1ZGNjNzM1Yjc5NWVlNDBkYmRlNDllMGVkMjA0MTkwOGRkOTYyOGYyOGNjNTRiMDQzMjdiOWI4Mzk4YjgzMTQzNWQ0ZDU3OTJhNDNhNzgzOTM2ODExZjdlYzNhZDljNzlmNGMxMjMzYmRlZWI3YmVkODlmZTYzNDJhNWE0ODJhYjRlNGQ0MmI5NDdlMDcyN2M2MGQ5ZTU0OGFkMTIzNDExNmJmMjJlNDYzMTk2OGRmNjgxNTQ4ODE3ZTA2ODk1MzZmYjZmNTdiY2I1Yzk1YzY4ODQ3ZTYwNGY0ZGIxYjIyYTNmYmU4MzhiNmEyZmYyYzUwZWIzN2Q4MGQ3ZGQzNGU1MTQ5OTA3MDBlNzc3YmI5NTY2OWRmNzgwYzRjOWZmNmU4ODRiMDIwM2YyNTQ1ZTc3OTBmNWQ4MWY5OWQ2NDM4Yzc2YjVmMzhmMGVhZmU3ZGYxZDYwYzM4NDA1ODc2ZTE5NGNjODE1NTg0OWFiYmYyMmExMjM3MzgyNzYzYWMzY2NkMjNkNTQ3OWIwMTRkNTBkM2ZiZDcwMzMwNzZkNWY3ZjkzZWRmOWY1YWQ3MTA1OTY4YzcwYzQzYzZjMmE0ZTk5YmYyYjdlOGZjYWY3ZjZkNWRjNDg5NzRlMWEwMGQ1ODgzN2Q4YzU5ZGQyYzA5NDRmYzY4NmU1MjYyMzE4NGZlNzA2MzQyYTQ3MWQ0NDdmNmZjYjA3MDUxNTkyZDIzNzFkNjU2ZWVkNzljNzIzOWRjMGNiYTgwNjc0N2MyMzc1ODI4YmZmNTI0NzUxYWI2ZjMwYjU5OTVjNTRhNmMxY2RmYmY3OGJkNzBlMjc2MGFkYWZmZTQzMWEzNmFlNjVkNTVmNThlMzBlZjFhYjliMDBjYmVkN2QwOTRjYmI3ODRjYWYwZTJhNDkzMjVkOGRiZWRlNDkxYmFjOTY5MTMxNGI1YzQxYWUxZmU5ZGQxMjYxMTUyMzFlMzk4ZjNhYTYyYjI3YWExZmU4M2ZlYzMyY2MwMWViZmE2MTQyYWQ0OWQzNWYzYTVlZjY0MzZhODM5OTU5N2YxZDFjMjYzYzYyNzYzYTM3NmM1ZmRmODYzZmIwODBjNDJjYWNhNzZkODUyNDQ2NmVkMGU2ZmVjM2Q5NTliOWQyYTdmZmRlNmQ0MWY0NDQ1NTRhZWJiZTYxODViYTkzNGNiYzM3ZjUwZmJjOGYxMjI3MjFlZjk1ZDRhMzA4MDE0NDM5MzM2ZWI0Y2RmMzhlY2YxZTkwZDYzZTljZjU0MGY0ZmEwMzdkYzg1MjcxNGMyZDdmOGE4YTk4NDYwZTczYzEwNjE3MjRmNmExYjA3NTM5ODVkY2QxNGMxZWVkN2NlNjA2ZWJhMmU1ZmFlY2M4MmI2YTZhMjI5YjdjODdkODZjNmI3NjJmMmFmYTUzZDA5ODgxMWNlM2Q3OGFkOTQ0YmE4ZjQyZjEyZGE3M2Q0MTA5MmNiYzhlYmFiYTY1YTBhYzdjNzQ0YTQ0YjhkYjlmZTRkZTFmMTI1MTExZmU1ZjE2ZDBlNjNkZDkwZjNmYjBmYmU3MWViMmE3ZDJhZmNlODk1ZDI1Y2VjZTgwMTg3NzIwZWRlNWVmMDg4ZGYxNWJjYzY1ZjE0ZjVkNDY1YTA1NWRhY2ExMzlkOTFmYWI0YjBkNGE0ZmE4ZDgzZTI1MmYzMGE2Y2EzMjIwNGVjZDM1MWZhZjgwYTNlYzhmNmQ2NzE5MjYyNGI1MWIwN2FkYzA3NDVjZjdhZGY3NDhlMzExZWI1YTA3ZWM1OWJjYmVmZjk1MjhkMDQ5ZTI3N2RkMzhhMGNiNjcwMzdiZjVjNjQ4YWIwZDU3YjA0ZjI0MDkyYmQzMTYxNDQwMzBkNDhhOTIxYjZlZjgzZGI4MjQ1NGZmMmE2ZDJhYWI1NTE1ZmY2NDA3NjE3Y2U2NGI5MDgxOWZiMzRjNTAwMzBjODk4MzBhY2U2YTVjY2QyMzY4NTdmMWNhMzIxNjVlYmFjOWZiOGVlNTVmOWYzNDcwNDU3OWY3Mjg2Y2ZkNGFiZjdiMzZlOTAyZTQ3NTY5ZmMzMDYwOGY4NDM2YmM2NGFlZGQwOTNkMjU0ZWQ5YzVkMTE4NjYwOGIxMzM3NDViODRmM2RlMWNlOGQ3YThlNDQyZDFlNmEyY2VhOTZhYmJhZDAyOWU2NzY1OWEwNzYxZTA2ZWIwODhiOWZjYTkwMjliNTc5ZDlhNGI1NjNlOTI0OWM1NDUwMWVlNGNlNzljZDgyYzQ2MWQ3NDdkOWY3MjYxODM4YzBjMGQ1NmYzMDhkNGFhZmFiZGM0MjBiZWYxMTllY2JlNTZhMGRlMWQ1YmIwNTEzYWZiMmUxZDY2N2ZjNGMyOGQzNzQyYzJlM2QwMDY1MWM3OGVmNjc3MjY4NzkzNTE2ZmU2ODU0OTViOGE2ODA4N2NmOWUwZjMyMGVhYjZiOWVmNDBiZDMxODNhZWFlMjczMGMyYjlkNjc4MjhlZGZkYWNlMTU0MzA3ZGQ0MDY5ZmY4YzgxNDhiYzg2MzAwNDhjNmIxZTNmZjRhZmJlMzdkMmEyZTEyMTExMmE3NWRlOTQxMzAzYmY4MTE2NTlhYzg5ODk0YmYxNDBhMzdhOTRlYTg0YTI5YzQzODBiOGJiYjE1ZGRjMzM4ODkwMDMyMzY2ZTk0MzRmNmI4ODI5NzEyYTRhMWZlMzcwZGM2NTU0YmZlOTFjYTNlYTljODEyYjA2MDFiOWMwMGJjNWUwMjFjNWVmZTFjMjJhZWIwNmVkNzE3NDg1MjU5Y2IwNjgwNmRlNzhlOTMyYjg0OWVhMDA2YzY1Y2MyOGFmNGE4OGEzNGU1MGQ2NGQ4Nzg4YzgwZTNiYzY0YzFiNTcwYmE3NjNlMzMxYmFhYzE4MGFjZjkwMzZiM2VhMmEyZWJkYzhjNjlmMjZlOGFjZDdjMGYxYmMyYmIxZmQ5MzU3MGM1Y2NjMDhlMmIxMDM2ZTFjOWU0NWI1YzZkMTZjMDliY2JiYTA1ZDhlMjhhNTgwOTgyNWRiZjgwMjExODE5ZjQxYmQ1MDA2MjVkMDdlNzU4OTJmODM4MTU5ZTg1NzVlY2UyYTQ5ZjE3NDAxYTMyZWU5OGUyZGMyODczZTIwNDQzMmNkNDI1ZTI2YTI4NjcwZDI2M2Q4ZDNiNDIyNTJkYzQxYWZhN2RmZjE5NzFmZjNhMGE0NWI3YTFkMDdhY2FhNmZiNDNlNjIxYjk0NTBiNGYxYjNhMTk0OTRjNTg0OWViNTcwOWI5NDlmMmZkODQ5ODZiMTg3NjE0ZWJlODNhYjVjYWJkZjNhZmYyMTRmODkwZWE1MzUyOTQ3MTBlZjhjYzk2NDQwYjYwZjcxYjkzOWI1ZGQ5NjI1MjgxOWFjZDk4ZDEyMTg3MmFmMDhhMTRiMTY4NGU3MjRkZWRlNjNjMTFjOWQ5Y2E4OGM3MzRkMDg0OGYzNTc4YWRlNjdhMGU2NmQ0M2M4Njc3NDRjYjc0M2ZlYTBmODVmM2UxZWRkMjI3MDczZTczZDQ3YjE5NGQwOGUyYTkyZGRmZGFkYzFmNjQwYTk2ZjRhMDZiMjg2NmNiMjhmMWZjNDI4YzQ4OWVkMTEwMWVmYjAzZGUxYjY2ZDY1OTg0OTYxZjZhMTJlOWY2NzljYjY3N2NhMjQxMGEwMjQ1ZjYxNTAyMzdiY2ZhYjUzOThiOGUwZTM2NDU0ZDgyY2Q1YzhmZTk1YzkwZDAxZTdjY2ZkZDI5ODlmYWE4ZTg2YzM0YmQzMGQ1ODBmNmFjOWQzMGUyYzhhMGNlZTEyYzE1MWExNDE1ZmFhYmZiMDgyNDBjN2EwYTllNDczODhmYWJhMDE2NzNkZjc0ODgyMjBlOTRlNjc4OGU0NzAyODkyOGI5YWJkMWFhMTY4OGEzYTQ0ODdmMzM2OGZhZDBhMGRhMzkxNTM5ZjI2ZDE5Y2M2ZGJjYzM2ODBlYjFkZmI0OWJkNDc5ZWQ2ZmM2NTYxNTA3Y2RjYjYxOTQ0YmMyMDkzZTZlZTFlNjE1ZDk4MTg3MGZjNDdmZWM2YjVhNTkzNzgwNjQ1ZGQ1NzNkMzZmYjJlZGNlMjMxZjQzYWIyZmQwYzZhOWI4MzcxYWZiYjE1NjQ0NGVkZDZkODE3YTRkODQzYzZlZThhODZlOTc5ZmQ0OTEwNDlmNGI2ZjQ5MTY4MThhZDhkMTFmNWJlZTYzOWJhZjAyYjAxMTk4ZmM4MGQ5ZDI0Y2UxOWZlZTc1MzZjMWUxNjc2ZmFkZTI1MGVkMGFkMzQ0YWY5MmZhZTI3Yjk1YjM4Y2NlOTZlYjJkY2MxMjU3ODMwZDRmYTIwZDJjMDYyMjliOWQ3ODBlMTNhZGVkNTMwZTFlZDU3MTU1N2FmNzIxZDZmOGM1MzZkM2ZjZjUxOTNlMjdmYzY5MTg2OTBjYjEyZTdkMzJhM2U2OTI5ZjgwNTUyN2YxYjQyYTcxNmIyY2JmMTM1MGEwOGMyZjk2ZjA5N2E5NmQ3MjFlZThiMjhlMmM0ODE5MDA4MmUyOTQ2MjNlODNiZjM0NzVjYWU0Y2Q1NWJhYzZhM2UxMTdjMjVkMDljY2NjNGZmMWJmMTg5ODJjOGFjNGNjZGZhMWUzNzdlN2U2ZjIxNGZlNzBlNGY2ZWI1MjNmNGZlZTcwNDdiNTRjOTJjZjRiZmU5MDEyNmE0MWI0NTY2M2JhY2VmMjcyNDliNDFhYWU4ZjhlNDZjYWZmMzEyOWRhMGI4MTkwODM4OTkzNWU2ZGNmNDYxNzczNzhkOTFlNTgwMDI3YzZmMWQwZTkwMmM5ZTBhZTc5Y2YzMDIzMTFkMzE1ZmE4YmM4YjZiOGJmNzFjYmQ1MjZkZDIwMDgwZjVkMWY4OWJkMGE2MTQ1ODBjOTg5MTM1MGQ2MjIyMzhmNzk1NjQ4M2Q5ZjRjYTMxZmI3YjI2NzhmNDRlODk1MTc2MGE0OGNkZGVmZDdlODA3ZmUzMjRhOWViMzZmMDI5MGZmZTAwYTg5YTI4MjZhZTZiNGIzMGY4N2UxNGI5YzM5NjQ1ZjE5MWQ1Y2JhNzcxNDA2ZjJjNWJlNmQwOTAxYTRlNjAyOWZlNmY4NjlhNDY2M2Y5YzVkMjcxOTQxODliOWQ3NGVlZWNmZjk0MmVjOTEwMzBhNzVkMzNkMzJkMGVmZjY5NTY1Njk4ZjczMmZjMjJmMGYxMzBlMTVkNDU0ZWEzY2E5NjhmMzc3NGRhYzAyZWE2MDQ5N2IyMGM2YTdjNmEzZGNlNWIwZGFkYmI4Yjc1NDNiZDdhOTNmYjQ1Yjc4ZjE3OTY4ZTY4MTI2YTY1Y2UzYzI5YzlkNTc1NzFlZjE1MWQ0YTZmZThjMTZjZjY4MGM2ZTllYzNkY2Y4MWM5ZWIyZjQ2ZTE0NDFiZTQ1YTQ2YmFk";
        EncryptManager encryptManager = new EncryptManager(privatekey, publickey);
        encryptManager.parseMobKey(mobKey);
        String data = encryptManager.decryptStr(content);
        System.out.println(data);
    }

}
